version: '3.4'

# The Production docker-compose file has to have the external/real IPs or DNS names for the services
# The ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP=192.168.88.248
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.
#
# IMPORTANT: Note that this compose file uses ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP instead of ESHOP_EXTERNAL_DNS_NAME_OR_IP

# Set ASPNETCORE_ENVIRONMENT= Development or Production, depending if you want to show up errors while testing.
#
# You need to start it with the following CLI command:
# docker compose -p eShopOnContainers -f docker-compose.yml -f docker-compose.prod.yml --env-file aws.env up

services:

  #seq:
  #  environment:
  #    - ACCEPT_EULA=Y

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    #ports:
    #  - "5433:1433"
    deploy:
      resources:        
        limits:
          cpus: '0.5'
          memory: 2Gb

  nosqldata:
  #  ports:
  #    - "27017:27017"  
    #volumes:
    #  - eshop-nosqldata:/data/db
    deploy:
      resources:        
        limits:
          cpus: '0.25'
          memory: 1Gb

  basketdata:
  #  ports:
  #    - "6379:6379"    
    #volumes:
    #  - eshop-basketdata:/data
    deploy:
      resources:        
        limits:
          cpus: '4'
          memory: 16Gb

  rabbitmq:
  #  ports:
  #    - "15672:15672"  
  #    - "5672:5672"    
    deploy:
      resources:        
        limits:
          cpus: '0.5'
          memory: 2Gb

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://webstatus.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - HealthChecksUI__HealthChecks__0__Name=WebMVC HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://webmvc.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__1__Name=WebSPA HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://webspa.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__2__Name=Web Shopping Aggregator GW HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://webshoppingagg.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__3__Name=Mobile Shopping Aggregator HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://mobileshoppingagg.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__4__Name=Ordering HTTP Check
      - HealthChecksUI__HealthChecks__4__Uri=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__5__Name=Basket HTTP Check
      - HealthChecksUI__HealthChecks__5__Uri=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__6__Name=Catalog HTTP Check
      - HealthChecksUI__HealthChecks__6__Uri=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__7__Name=Identity HTTP Check
      - HealthChecksUI__HealthChecks__7__Uri=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__8__Name=Payments HTTP Check
      - HealthChecksUI__HealthChecks__8__Uri=http://payment-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__9__Name=Ordering SignalRHub HTTP Check
      - HealthChecksUI__HealthChecks__9__Uri=http://ordering-signalrhub.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - HealthChecksUI__HealthChecks__10__Name=Ordering HTTP Background Check
      - HealthChecksUI__HealthChecks__10__Uri=http://ordering-backgroundtasks.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
    ports:
      - "80"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - SpaClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5104
      - XamarinCallback=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback      #localhost do not work for UWP login, so we have to use "external" IP always
      - ConnectionString=${ESHOP_AZURE_IDENTITY_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word}
      - MvcClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5100              
      - BasketApiClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileShoppingAggClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebShoppingAggClient=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5121
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - ConnectionString=${ESHOP_AZURE_REDIS_BASKET_DB:-basket.data}
      - identityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}              
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/basket-api
      - GRPC_PORT=81
      - PORT=80

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word}
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureStorageAccountName=${ESHOP_AZURE_STORAGE_CATALOG_NAME}
      - AzureStorageAccountKey=${ESHOP_AZURE_STORAGE_CATALOG_KEY}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - AzureStorageEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - GRPC_PORT=81
      - PORT=80
      - PATH_BASE=/catalog-api

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - ConnectionString=${ESHOP_AZURE_ORDERING_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word}
      - identityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}              
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose
      - Serilog__MinimumLevel__Override__ordering-api=Verbose
      - PATH_BASE=/ordering-api
      - GRPC_PORT=81
      - PORT=80

  ordering-backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://ordering-backgroundtasks.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - ConnectionString=${ESHOP_AZURE_ORDERING_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word}
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - UseCustomizationData=True
      - AzureServiceBusEnabled=False
      - CheckUpdateTime=30000
      - GracePeriodTime=1
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose

  #ordering-signalrhub:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://ordering-signalrhub.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
  #    - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
  #    - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
  #    - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
  #    - AzureServiceBusEnabled=False
  #    - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
  #    - OrchestratorType=${ORCHESTRATOR_TYPE}
  #    - identityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://payment-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      - EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      - AzureServiceBusEnabled=False
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - Serilog__MinimumLevel__Override__payment-api.IntegrationEvents.EventHandling=Verbose
      - Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ=Verbose

  #webhooks-api:
  #  environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://webhooks-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
      #- ConnectionString=${ESHOP_AZURE_WEBHOOKS_DB:-Server=sqldata;Database=Microsoft.eShopOnContainers.Services.WebhooksDb;User Id=sa;Password=Pass@word}
      #- EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      #- EventBusUserName=${ESHOP_SERVICE_BUS_USERNAME}
      #- EventBusPassword=${ESHOP_SERVICE_BUS_PASSWORD}
      #- IdentityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
      #- IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105

  #webhooks-client:
  #  environment:
  #    - ASPNETCORE_URLS=http://webhooks-client.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
  #    - Token=6168DB8D-DC58-4094-AF24-483278923590      # Webhooks are registered with this token (any value is valid) but the client won't check it
  #    - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
  #    - CallBackUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5114
  #    - WebhooksUrl=http://webhooks-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - SelfUrl=http://webhooks-client.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/

  #webshoppingapigw:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - IdentityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}              
  #  #volumes:
  #  #  - ./ApiGateways/Web.Bff.Shopping/apigw:/app/configuration
  
  #webshoppingagg:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - urls__basket=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - urls__catalog=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - urls__orders=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - urls__identity=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - urls__grpcBasket=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
  #    - urls__grpcCatalog=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
  #    - urls__grpcOrdering=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
  #    - CatalogUrlHC=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - OrderingUrlHC=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - IdentityUrlHC=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - BasketUrlHC=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - PaymentUrlHC=http://payment-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105          
  
  #webspa:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://webspa.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
  #    - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
  #    - PurchaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
  #    - IdentityUrlHC=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - UseCustomizationData=True
  #    - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
  #    - OrchestratorType=${ORCHESTRATOR_TYPE}
  #    - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202

  #webmvc:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://webmvc.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:80
  #    - PurchaseUrl=http://webshoppingapigw.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
  #    - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
  #    - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
  #    - IdentityUrlHC=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
  #    - UseCustomizationData=True
  #    - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
  #    - OrchestratorType=${ORCHESTRATOR_TYPE}
  #    - UseLoadTest=${USE_LOADTEST:-False}

  #mobileshoppingapigw:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - IdentityUrl=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}         
  #  #volumes:
  #  #  - ./ApiGateways/Mobile.Bff.Shopping/apigw:/app/configuration

  #mobileshoppingagg:
  #  environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      #- urls__basket=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
      #- urls__catalog=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
      #- urls__orders=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
      #- urls__identity=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}
      #- urls__grpcBasket=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
      #- urls__grpcCatalog=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
      #- urls__grpcOrdering=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}:81
      #- CatalogUrlHC=http://catalog-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      #- OrderingUrlHC=http://ordering-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      #- IdentityUrlHC=http://identity-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      #- BasketUrlHC=http://basket-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      #- PaymentUrlHC=http://payment-api.${ESHOP_PROD_INTERNAL_DNS_NAME_OR_IP}/hc
      #- IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105

## attempt to fix the healthcheck, but need to figure out the name of the target group that is created for webstatus
x-aws-cloudformation:
  Resources:
    WebstatusTCP80TargetGroup:
      Properties:
        HealthCheckPath: /hc-ui